version: "2.1"
services:
  spark:
    build:
      dockerfile: Dockerfile
      context: ..
      args:
        - PYTHON_VERSION=3.8.12
        - SPARK_VERSION=3.1.2
        - HADOOP_VERSION=3.2
    volumes:
      - ./data:/data
  driver:
    extends:
      service: spark
    depends_on:
      - master
      - worker_bear
      - worker_hawk
  ipython:
    extends:
      service: spark
    command: spark-ipython
  jupyter:
    extends:
      service: spark
    command: spark-jupyter
    ports:
      - 7000:7000
    environment:
      - SPARK_JARS=postgresql-9.4.1207.jar
  master:
    extends:
      service: spark
    command: master
    ports:
      - 8080:8080
      - 7077:7077
  worker_hawk:
    extends:
      service: spark
    depends_on:
      - spark
    command: worker
    environment:
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_WORKER_PORT=7078
    ports:
      - 8081:8081
      - 7078:7078
  worker_bear:
    extends:
      service: spark
    depends_on:
      - master
    command: worker
    environment:
      - SPARK_WORKER_WEBUI_PORT=8082
      - SPARK_WORKER_PORT=7079
    ports:
      - 8082:8082
      - 7079:7079