name: Deploy
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python: ["3.7.11", "3.8.12", "3.9.7"]
        spark: ["2.4.8", "3.0.3", "3.1.2"]
        hadoop: ["2.7", "3.2"]
    env:
      PYTHON_VERSION: ${{ matrix.python }}
      SPARK_VERSION: ${{ matrix.spark }}
      HADOOP_VERSION: ${{ matrix.hadoop }}
    steps:
      - uses: actions/checkout@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build image
        run: |
          docker build \
            --build-arg SPARK_VERSION=$SPARK_VERSION \
            --build-arg PYTHON_VERSION=$PYTHON_VERSION \
            --build-arg HADOOP_VERSION=$HADOOP_VERSION \
            -t vmalashkov/apache-spark:spark-$SPARK_VERSION-h${HADOOP_VERSION}-py-$PYTHON_VERSION .

      - name: Push image
        run: |
          docker push vmalashkov/apache-spark:spark-$SPARK_VERSION-h${HADOOP_VERSION}-py-$PYTHON_VERSION
